/**
 * Isiwara Aura - Shared Functional Utilities, POS Intake Builder, and Print Engine Module
 */

/**
 * Custom Notification Toast Engine
 * @param {string} title - Header text for message
 * @param {string} message - Body text detail
 */
function triggerCustomSwalNotification(title, message) {
    const titleNode = document.getElementById('swal-injected-title');
    const msgNode = document.getElementById('swal-injected-msg');
    const containerNode = document.getElementById('custom-swal-container');
    
    if (titleNode) titleNode.innerText = title;
    if (msgNode) msgNode.innerText = message;
    if (containerNode) containerNode.classList.add('show');
}

/**
 * Dismisses the notification box overlay safely
 */
function dismissCustomSwalPopup() {
    const containerNode = document.getElementById('custom-swal-container');
    if (containerNode) containerNode.classList.remove('show');
}

/**
 * Native Bootstrap 5 Safe Modal Show Handler
 * @param {string} modalElementId - Target DOM Element ID
 */
function safeOpenModal(modalElementId) {
    const targetElement = document.getElementById(modalElementId);
    if (!targetElement) return;
    try {
        const modalInstance = new bootstrap.Modal(targetElement);
        modalInstance.show();
    } catch (err) {
        targetElement.style.display = "block";
        targetElement.classList.add("show");
    }
}

/**
 * Native Bootstrap 5 Safe Modal Hide Handler
 * @param {string} modalElementId - Target DOM Element ID
 */
function safeCloseModal(modalElementId) {
    const targetElement = document.getElementById(modalElementId);
    if (!targetElement) return;
    try {
        const activeInstance = bootstrap.Modal.getInstance(targetElement);
        if (activeInstance) activeInstance.hide();
    } catch (e) {
        console.warn("Native modal instance lookup exception. Running manual DOM patch layers.");
    }
    
    targetElement.style.display = "none";
    targetElement.classList.remove("show");
    
    const lingeringBackdrop = document.querySelector('.modal-backdrop');
    if (lingeringBackdrop) lingeringBackdrop.remove();
}

/**
 * Formats seconds integers into standard running clock strings MM:SS
 * @param {number} totalSeconds 
 * @returns {string} Formatted chronological time text
 */
function formatSecondsToMinutesString(totalSeconds) {
    const minutesCalculated = Math.floor(totalSeconds / 60);
    const secondsCalculated = totalSeconds % 60;
    return `${minutesCalculated.toString().padStart(2, '0')}:${secondsCalculated.toString().padStart(2, '0')}`;
}

/**
 * Generates an audible completion beep alert using browser audio synthesis hardware frequencies
 */
function triggerNativeAudioHardwareBeep() {
    try {
        const AudioContextClass = window.AudioContext || window.webkitAudioContext;
        const audioCtxInstance = new AudioContextClass();
        const oscillatorNode = audioCtxInstance.createOscillator();
        const systemGainNode = audioCtxInstance.createGain();
        
        oscillatorNode.connect(systemGainNode);
        systemGainNode.connect(audioCtxInstance.destination);
        
        oscillatorNode.type = 'sine';
        oscillatorNode.frequency.value = 880; // High A5 Pitch Frequency Tone
        systemGainNode.gain.setValueAtTime(0.4, audioCtxInstance.currentTime);
        
        oscillatorNode.start();
        oscillatorNode.stop(audioCtxInstance.currentTime + 0.45); // 450 Milliseconds signal duration burst
    } catch (err) {
        console.warn("Hardware audio synthesis execution blocked by browser permissions context security flags.");
    }
}

// =========================================================================
// (H) UNIVERSAL BULK INTAKE INTERFACE LOGIC & POS ENGINE BUILDER
// =========================================================================

/**
 * Initializes and filters the full-screen Universal Bulk Intake POS workspace.
 * Explicitly locks out currently active rooms and busy therapists from dropdown menus.
 */
function openBulkIntakeModal() {
    activeGuestCountInModal = 0;
    const rowsContainer = document.getElementById('dynamic-guests-rows-container');
    if (rowsContainer) rowsContainer.innerHTML = '';
    
    // Retrieve exclusion lists actively generated by running manage.js timers
    const lockedRooms = JSON.parse(sessionStorage.getItem('activeLockedRooms') || '[]');
    const lockedStaff = JSON.parse(sessionStorage.getItem('activeLockedStaff') || '[]');

    // Enforce business rules filters on data caches
    const filteringRooms = cacheRooms.filter(r => r.fields['Room Type'] !== 'Special' && !lockedRooms.includes(r.fields['Room Number']));
    const filteringStaff = cacheTherapists.filter(s => !lockedStaff.includes(s.fields['Name']));

    // Hydrate parent selectors inputs components
    const roomSelect = document.getElementById('bulkIntakeRoomSelect');
    if (roomSelect) {
        roomSelect.innerHTML = '<option value="">-- Choose Target Room Suite Location --</option>' + 
            filteringRooms.map(r => `<option value="${r.id}" data-beds="${r.fields['Beds Count']}">${r.fields['Room Number']} (${r.fields['Beds Count']} Beds Capacity - ${r.fields['Room Type']})</option>`).join('');
    }

    const introSelect = document.getElementById('bulkIntakeIntroducerSelect');
    if (introSelect) {
        introSelect.innerHTML = '<option value="">-- Link Active Partner Profile --</option>' + 
            cacheIntroducers.map(i => `<option value="${i.id}">${i.fields['Full Name']}</option>`).join('');
    }

    // Temporarily cache working staff lines into session space for sub-guest split rows population calls
    sessionStorage.setItem('tempFilterStaffDropdownOptions', JSON.stringify(filteringStaff));

    // Seed initial row automatically on entry window launch
    addNewGuestAllocationRowMarkup();
    safeOpenModal('bulkIntakeModal');
}

/**
 * Dynamically appends a multi-guest split row sub-allocation input field grouping matrix (Up to 5 Splits maximum).
 */
function addNewGuestAllocationRowMarkup() {
    if (activeGuestCountInModal >= 5) return;
    activeGuestCountInModal++; 
    const idx = activeGuestCountInModal;

    const staffPool = JSON.parse(sessionStorage.getItem('tempFilterStaffDropdownOptions') || '[]');
    const container = document.getElementById('dynamic-guests-rows-container');
    if (!container) return;

    const rowTemplate = `
        <div class="row g-2 align-items-end mb-3 border-bottom pb-3 guest-input-row animate-fade-in" id="bulkGuestRowIndex_${idx}">
            <div class="col-md-2">
                <label class="small text-muted font-monospace mb-1">Guest Name Splitting Identity</label>
                <input type="text" class="form-control form-control-sm item-guest-name" required>
            </div>
            <div class="col-md-2">
                <label class="small text-muted font-monospace mb-1">Therapy Package Menu</label>
                <select class="form-select form-select-sm item-treatment-select" onchange="calculateAggregatedBulkInvoicedSum()" required>
                    <option value="">-- Select Package --</option>
                    ${cacheTreatments.map(t => `<option value="${t.id}" data-price="${t.fields.Price}" data-duration="${t.fields['Duration in Minutes']}">${t.fields['Treatment Name']} (රු. ${t.fields.Price})</option>`).join('')}
                </select>
            </div>
            <div class="col-md-2">
                <label class="small text-muted font-monospace mb-1">Therapist Assignment</label>
                <select class="form-select form-select-sm item-therapist-select" required>
                    <option value="">-- Assign Staff --</option>
                    ${staffPool.map(s => `<option value="${s.id}">${s.fields.Name}</option>`).join('')}
                </select>
            </div>
            <div class="col-md-2">
                <label class="small text-muted font-monospace mb-1">Herbal Steam Session Routing</label>
                <select class="form-select form-select-sm item-steam-routing">
                    <option value="No">No (Skip Post Chamber)</option>
                    <option value="Yes">Yes (Process Steam Afterward)</option>
                </select>
            </div>
            <div class="col-md-2">
                <label class="small text-muted font-monospace mb-1">Manual VAS Fee (රු.)</label>
                <input type="number" class="form-control form-control-sm item-vas-fee" value="0" min="0" onkeyup="calculateAggregatedBulkInvoicedSum()">
            </div>
            <div class="col-md-1">
                <label class="small text-muted font-monospace mb-1">Discount %</label>
                <input type="number" class="form-control form-control-sm item-discount-pct" value="0" min="0" max="100" onkeyup="calculateAggregatedBulkInvoicedSum()">
            </div>
            <div class="col-md-1">
                <button type="button" class="btn btn-sm btn-outline-danger w-100" onclick="removeGuestRowAllocationLine(${idx})">✕</button>
            </div>
        </div>
    `;
    container.insertAdjacentHTML('beforeend', rowTemplate);
    calculateAggregatedBulkInvoicedSum(); 
    verifyRoomBedCapacityConstraints();
}

/**
 * Removes a guest allocation row line from the checkout split pool matrix.
 */
function removeGuestRowAllocationLine(idx) {
    const targetingRowNode = document.getElementById(`bulkGuestRowIndex_${idx}`); 
    if (targetingRowNode) { 
        targetingRowNode.remove(); 
        activeGuestCountInModal--; 
    }
    calculateAggregatedBulkInvoicedSum(); 
    verifyRoomBedCapacityConstraints();
}

/**
 * Calculates row subtotals and checks the dynamic currency display flag.
 * Math Formula: Subtotal = (Package Base Price + Value Added Services Fee) * (1 - (Discount Percentage / 100))
 */
function calculateAggregatedBulkInvoicedSum() {
    let aggregatedRupeeTotal = 0;
    
    document.querySelectorAll('.guest-input-row').forEach(row => {
        const packageSelect = row.querySelector('.item-treatment-select');
        const packageBasePrice = parseFloat(packageSelect.options[packageSelect.selectedIndex]?.getAttribute('data-price')) || 0;
        const valueAddedServicesFee = parseFloat(row.querySelector('.item-vas-fee').value) || 0;
        const discountPercentage = parseFloat(row.querySelector('.item-discount-pct').value) || 0;
        
        const lineNetLiabilityValue = (packageBasePrice + valueAddedServicesFee) * (1 - (discountPercentage / 100));
        aggregatedRupeeTotal += lineNetLiabilityValue;
    });

    const displayLabelNode = document.getElementById('lblBulkTotalCalculation');
    if (!displayLabelNode) return;

    const outputMode = document.querySelector('input[name="currencySelectionNode"]:checked')?.value || 'LKR';
    if (outputMode === 'USD') {
        // Formats header labels strings strictly without executing backend exchange rate conversions anomalies values
        displayLabelNode.innerText = `$ ${aggregatedRupeeTotal.toLocaleString(undefined, { minimumFractionDigits: 2 })} (Invoice Label USD Mode)`;
    } else {
        displayLabelNode.innerText = `රු. ${aggregatedRupeeTotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}`;
    }
}

/**
 * Prevents overcrowding by evaluating split row additions against available room bed lines limits.
 */
function verifyRoomBedCapacityConstraints() {
    const select = document.getElementById('bulkIntakeRoomSelect'); 
    const feedbackTextNode = document.getElementById('room-capacity-alert');
    if (!select || !feedbackTextNode || !select.value) return;
    
    const availableBedsLimitCount = parseInt(select.options[select.selectedIndex].getAttribute('data-beds'), 10) || 1;
    feedbackTextNode.innerText = (activeGuestCountInModal > availableBedsLimitCount) ? 
        `⚠️ Warning: Combined sub-guests splits layout counts (${activeGuestCountInModal}) exceeds available bed lines capacity allocated to this room (${availableBedsLimitCount} Beds maximum).` : '';
}

/**
 * Toggles visibility frames of dynamic internal custom sub-forms elements inside POS wizard workspaces.
 */
function toggleIntroducerVisibilityFields() {
    const inputChoiceMode = document.getElementById('bulkIntakeIntroducerType').value;
    const existingPane = document.getElementById('section-existing-introducer');
    const onTheFlyPane = document.getElementById('section-new-introducer');

    if (existingPane) existingPane.style.display = (inputChoiceMode === 'Existing') ? 'block' : 'none';
    if (onTheFlyPane) onTheFlyPane.style.display = (inputChoiceMode === 'New') ? 'flex' : 'none';
}
